In [17]:
import numpy as np
vector = np.random.randint(1, 21, size=15)


In [18]:
reshaped_vector = vector.reshape(3, 5)
reshaped_vector


array([[11, 13, 16,  3, 18],
       [ 5, 16, 14,  6, 14],
       [ 3, 20, 18,  7,  5]])

In [19]:
shape = reshaped_vector.shape
print(shape)

(3, 5)


In [20]:
for i in range(reshaped_vector.shape[0]):
    max_index = reshaped_vector[i].argmax()  # Find the index of the maximum value in the current row
    reshaped_vector[i, max_index] = 0  # Replace the maximum value with 0

print(reshaped_vector)




[[11 13 16  3  0]
 [ 5  0 14  6 14]
 [ 3  0 18  7  5]]


B

In [21]:
array_2d = np.zeros((4, 3), dtype=np.int32)
array_2d

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [24]:
shape = array_2d.shape
type = type(array_2d)
dtype = array_2d.dtype


B

In [26]:
a = np.array([[3, -2], [1, 0]])


In [28]:
eigenvalues, eigenvectors = np.linalg.eig(a)


C

In [29]:
a1 = np.array([[0, 12], [3, 4]])


In [30]:
diagonal_sum = np.trace(a1)


D

In [31]:
a2 = np.array([[12, 3], [4, 5], [6, 7]])


In [33]:
modified_array = a2.reshape(2, 3)
modified_array

array([[12,  3,  4],
       [ 5,  6,  7]])